###################################################################
# +-------------------------------------------------------------+ #
# |                         Collections                         | #
# |                   Made with <3 by sieadev                   | #
# +-------------------------------------------------------------+ #
###################################################################

###################################################################
# -------------------------- Donate <3 -------------------------- #
# ------------------ https://ko-fi.com/sieadev ------------------ #
###################################################################

###################################################################
# --------------------------- STORAGE --------------------------- #
###################################################################
storage: "MYSQL"
database:
  ip: ""
  name: ""
  user: ""
  password: ""

###################################################################
# --------------------- Language / Messages --------------------- #
###################################################################
# All messages can be individually modified in "messages.yml".
# Language support with presets will be added in the future.
# Stay tuned!