name: Collections
version: '${project.version}'
main: dev.siea.collections.Collections
api-version: '1.20'
load: STARTUP
authors: [siea]
website: https://projects.siea.dev/collections
softdepend:
  - PlaceholderAPI
commands:
  collections:
    permission: collections.overview
    description: View your active collections
  delivery:
    permission: collections.openDeliveryGUI
    description: Open a DeliveryGUI
    usage: "/delivery <id> <player_name/player_uuid>"